- server/migrations/20220114094830-create-posts.js
- server/migrations/20220114094920-create-addressees.js
- server/seeders/20220114064325-was.js
Create schema and seed for addressees.
Db schema should be stable for now.
.
> feat(addressees): create schema and seed for addressees

- client/src/components/Header/Header.component.tsx
- client/src/pages/About/About.component.tsx
- client/src/routes.tsx
- client/src/theme/components/About.ts
- client/src/theme/components/index.ts
Create new About page, which links from the Header
> feat(about): new about page

- client/src/components/Banner/Banner.component.tsx
- client/src/components/EndorserModal/EndorserModal.component.tsx
- client/src/components/Hero/Hero.component.tsx
- client/src/components/PetitionCard/PetitionCard.component.tsx
- client/src/components/PostSignatures/PostSignatures.component.tsx
- client/src/components/PreviewBanner/PreviewBanner.component.tsx
- client/src/components/PublishButton/PublishButton.component.tsx
- client/src/components/SgidButton/SgidButton.component.tsx
- client/src/components/SignForm/SignForm.component.tsx
- client/src/components/SignatureModal/SignatureModal.component.tsx
- client/src/components/SubscriptionModal/SubscriptionModal.component.tsx
- client/src/components/SuccessBanner/SuccessBanner.component.tsx
- client/src/pages/EditPostForm/EditPostForm.component.tsx
- client/src/pages/Post/Post.component.tsx
- client/src/pages/PostForm/PostForm.component.tsx
- client/src/routes.tsx
- client/src/services/AuthService.ts
- client/src/services/PostService.ts
- client/src/theme/components/PetitionCard.ts
- client/src/theme/components/Post.ts
- server/src/bootstrap/index.ts
- server/src/modules/auth/auth.controller.ts
- server/src/modules/auth/auth.routes.ts
- server/src/modules/auth/auth.service.ts
- server/src/modules/post/post.controller.ts
- server/src/modules/post/post.routes.ts
- server/src/modules/post/post.service.ts
- server/src/modules/signatures/signature.controller.ts
- server/src/modules/signatures/signature.service.ts
- server/src/types/post-type.ts
This PR largely contains
- Preview pages
- Endorser flows
- Endorsers must use full name
- Edit petition
- Change badge text (Note: to include more status types in the schema)
> feat(preview): preview pages

- client/src/components/Header/Header.component.tsx
Fixes button alignment in header
> style(header): align header buttons to the right

- client/src/pages/Guidelines/Guidelines.component.tsx
- client/src/theme/components/About.ts
> feat(guidelines): update text

- client/src/components/Header/Header.component.tsx
- client/src/pages/Anonymity/Anonymity.component.tsx
- client/src/routes.tsx
- server/src/bootstrap/index.ts
Create Ensuring Anonymity page
> feat(anonymity): create anonymity page

- client/src/components/RichText/RichTextEditor.module.scss
Allow scroll in the rich text editor
> fix(rte): allow overflow

- client/public/index.html
- client/src/components/SignForm/SignForm.component.tsx
> chore(client): disable endorse button and update index

- client/src/components/PostSignatures/PostSignatures.component.tsx
- client/src/pages/Post/Post.component.tsx
> chore(post/postsignature): recent activity use LIFO, change updates text

- client/src/App.tsx
- client/src/components/EnvBanner/EnvBanner.component.tsx
- client/src/hooks/useEnvironment.ts
- client/src/services/EnvService.ts
- server/src/bootstrap/config/banner.ts
- server/src/bootstrap/config/googleAnalytics.ts
- server/src/bootstrap/index.ts
- server/src/modules/environment/__tests__/env.controller.spec.ts
- server/src/modules/environment/__tests__/env.routes.spec.ts
- server/src/modules/environment/env.controller.ts
- server/src/modules/environment/env.routes.ts
- server/src/routes/index.ts
- shared/src/types/api/env.ts
- shared/src/types/api/index.ts
Reinstate env service by:
- porting over the env service (server)
- porting over the env banner component (client)
> refactor(env): reinstate env service

- client/src/components/HowItWorks/HowItWorks.component.tsx
- client/src/components/PetitionCard/PetitionCard.component.tsx
- client/src/components/ScrollToTop/ScrollToTop.component.tsx
- client/src/index.tsx
- client/src/pages/Post/Post.component.tsx
> feat(scrolltotop): scroll to top by default

- client/src/pages/Anonymity/Anonymity.component.tsx
- client/src/theme/components/Anonymity.ts
- client/src/theme/components/index.ts
> feat(anonymity): build static page for explaining anonymity

- client/src/components/Banner/Banner.component.tsx
- client/src/components/PreviewBanner/PreviewBanner.component.tsx
- client/src/components/SignForm/SignForm.component.tsx
- client/src/pages/Post/Post.component.tsx
- client/src/pages/Post/PostSection/PostCell/PostCell.component.tsx
- client/src/pages/PostForm/FormFields/PetitionBodyForm.tsx
- PostForm: reorder info box to be below question prompt
- PostForm: reorder questions to mirror preview
- PreviewBanner: make sticky
- Preview: Show different view for petition owner
> style(client): change client view for better UX

- client/src/components/AnonymityBanner/AnonymityBanner.component.tsx
Adjust top and bottom margins of anonymity banner, remove height
> fix(anonymitybanner): adjust margins

- client/src/components/Banner/Banner.component.tsx
- client/src/components/Header/Header.component.tsx
- client/src/components/PostSignatures/PostSignature.component.tsx
- client/src/components/PreviewBanner/PreviewBanner.component.tsx
- client/src/components/SuccessBanner/SuccessBanner.component.tsx
- client/src/theme/components/About.ts
- client/src/theme/components/Anonymity.ts
- client/src/theme/components/Post.ts
Build mobile view for the following pages:
- About
- Anonymity
- View Petitions
- Preview Petitions
Site should be mostly mobile-friendly now.
> style(mobile): build mobile view 

- client/src/components/HowItWorks/HowItWorksBanner.component.tsx
- client/src/pages/About/About.component.tsx
- client/src/pages/Guidelines/Guidelines.component.tsx
Add links and graphics to homepage, update text.
`HowItWorksBanner` components takes in a parameter which specifies the grid of 3
> feat(about): add links and graphics

- client/src/components/PreSignModal/PreSignModal.component.tsx
- client/src/components/SgidButton/SgidButton.component.tsx
- client/src/components/SignForm/SignForm.component.tsx
- client/src/components/SignatureModal/SignatureModal.component.tsx
- client/src/contexts/AuthContext.tsx
- client/src/pages/Post/Post.component.tsx
- server/src/modules/auth/auth.controller.ts
- shared/src/types/api/auth.ts
Add modal before signing confirmation, to inform users that Singpass and potentially their full name will be used.
> feat: add pre-sign modal

- client/src/components/PreSignModal/PreSignModal.component.tsx
> fix(presignmodal): update text

- client/src/components/SignForm/SignForm.component.tsx
> style(signbutton): center sign button for mobile view

- client/src/pages/Anonymity/Anonymity.component.tsx
Add hyperlink to Ensuring Anonymity page
> fix(anonymity): add link

- client/src/api/types/addressee.ts
- client/src/api/types/auth.ts
- client/src/api/types/common.ts
- client/src/api/types/post.ts
- client/src/api/types/signature.ts
- client/src/components/PetitionCard/PetitionCard.component.tsx
- client/src/components/PostSignatures/PostSignature.component.tsx
- client/src/services/SignatureService.ts
Post-hackathon, clean up our type definitions, using shared types where we mean to
> refactor(api-client): use Post, Signature, Addresee shared types

- client/src/components/HowItWorks/HowItWorksBanner.component.tsx
- client/src/pages/About/About.component.tsx
As title says: Update text in about page to reference REACH Singapore.
> chore(about): update text to refer to REACH Singapore

- client/src/pages/About/About.component.tsx
As title says: Update text in about page to reference REACH Singapore.
> chore(about): update about text to refer to REACH Singapore

- client/src/components/Hero/Hero.component.tsx
- client/src/components/PetitionGrid/PetitionGrid.component.tsx
- client/src/theme/components/Hero.ts
- client/src/theme/components/PetitionGrid.ts
As title says.
Minor housekeeping: to fix errors thrown by react in console. For example, rendering list items should have a unique key prop.
> fix(console): miscellaneous react console errors

- secrets-check.sh
Fixes #51 
Port opengovsg/askgovsg#1348 and opengovsg/askgovsg#1135 to petitions
> chore(secrets-check): fixup regex, improve msgs

- server/package-lock.json
- server/package.json
> build(deps): add uuid
